# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

os: osx
osx_image: xcode11.3
language: ruby
cache: bundler

# don't build twice
if: tag IS blank

env:
  global:
    - TRAVIS_TAG=nightly-2020-08-16-0-travis-homebrew-cpp
    - ARROW_FORMULA=./arrow/dev/tasks/homebrew-formulae/apache-arrow.rb

before_script:
- git clone --no-checkout https://github.com/apache/arrow arrow
- git -C arrow fetch -t https://github.com/apache/arrow master
- if [ $CROSSBOW_USE_COMMIT_ID = true ]; then git -C arrow checkout 597ad62aeae9c07ec38a83720d436ae8f0322d0d; else git -C arrow checkout FETCH_HEAD; fi
# Pin the current commit in the formula to test so that we're not always pulling from master
- |
  sed -i.bak -E -e 's@https://github.com/apache/arrow.git"$@https://github.com/apache/arrow.git", revision: "597ad62aeae9c07ec38a83720d436ae8f0322d0d"@' $ARROW_FORMULA && rm -f $ARROW_FORMULA.bak
# Sometimes crossbow gives a remote URL with .git and sometimes not. Make sure there's only one
- sed -i.bak -E -e 's@.git.git@.git@' $ARROW_FORMULA && rm -f $ARROW_FORMULA.bak
- brew update
- brew uninstall --ignore-dependencies boost
- brew --version
- brew unlink python@2
- brew config
- brew doctor || true
- brew audit $ARROW_FORMULA
script:
- brew install -v --HEAD $ARROW_FORMULA
- brew test $ARROW_FORMULA