# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

os: linux
arch: arm64
dist: bionic
language: minimal

addons:
  apt:
    packages:
      - libgit2-dev
      - python3-pip
      - rake

services:
  - docker

# don't build twice
if: tag IS blank

env:
  global:
    - APT_TARGETS=centos-7-aarch64
    - ARROW_VERSION=1.1.0.dev34
    - BUILD_REF=2c362d6fcc0e29bd5b9ab2d5c62d0d759b44404d
    - TRAVIS_TAG=actions-487-travis-centos-7-aarch64
    - YUM_TARGETS=centos-7-aarch64

before_script:
  - git clone --no-checkout https://github.com/kszucs/arrow.git arrow
  - git -C arrow fetch -t https://github.com/kszucs/arrow.git maint-1.0.x
  - git -C arrow checkout FETCH_HEAD

script:
  - pushd arrow/dev/tasks/linux-packages
  - rake version:update
  - |
    rake docker:pull || :
  - rake BUILD_DIR=build yum:build
  - sudo rm -rf */*/build
  - popd

after_success:
  - pushd arrow/dev/tasks/linux-packages
  - |
    docker login -u "${DOCKERHUB_USER}" \
                 -p "${DOCKERHUB_TOKEN}" || :
  - |
    rake docker:push || :
  - popd
  - |
    sudo -H pip3 install \
      "click>=7.1" \
      github3.py \
      jinja2 \
      jira \
      pygit2==0.26.4 \
      ruamel.yaml \
      setuptools_scm \
      toolz
  - |
    python3 arrow/dev/tasks/crossbow.py \
      --queue-path . \
      --queue-remote https://github.com/ursa-labs/crossbow \
      upload-artifacts \
      --pattern "**/*.rpm" \
      --sha actions-487-travis-centos-7-aarch64 \
      --tag actions-487-travis-centos-7-aarch64